#!/bin/bash

readonly PROJECT_BASENAME=mongodb
readonly NUMBER_OF_PROJECTS=6
readonly OCP_TEMPLATE=mongodb-persistent-ocs
readonly MONGODB_MEMORY_LIMIT=4Gi
readonly PV_SIZE=10Gi
readonly MONGODB_VERSION=3.6
readonly YCSB_WORKLOAD=workloadb
readonly YCSB_DISTRIBUTION=uniform
readonly YCSB_RECORDCOUNT=4000000
readonly YCSB_OPERATIONCOUNT=4000000
readonly YCSB_THREADS=8
readonly RUN_NAME=${1}
start_from=${2}
readonly RUN_DIR=$(dirname $0)
log_dir="${RUN_DIR}/${RUN_NAME}"

if [[ ! -d "${log_dir}" ]]; then
  mkdir "$log_dir"
fi

for ((i=1; i<=${NUMBER_OF_PROJECTS}; i++))
do
  PROJECT_NAME=${PROJECT_BASENAME}-${start_from}
  echo "working on project ${PROJECT_NAME}"
  ${RUN_DIR}/create_and_load ${PROJECT_NAME} ${OCP_TEMPLATE} ${MONGODB_MEMORY_LIMIT} ${PV_SIZE} ${MONGODB_VERSION} ${YCSB_WORKLOAD} ${YCSB_DISTRIBUTION} ${YCSB_RECORDCOUNT} ${YCSB_OPERATIONCOUNT} ${YCSB_THREADS} ${log_dir} &
  (( ++start_from ))
done
