#!/bin/bash

readonly PROJECT_NAME=${1}
readonly YCSB_WORKLOAD=${2}
readonly YCSB_DISTRIBUTION=${3}
readonly YCSB_RECORDCOUNT=${4}
readonly YCSB_OPERATIONCOUNT=${5}
readonly YCSB_THREADS=${6}
readonly LOG_DIR=${7}
readonly MONGODB_USER=redhat
readonly MONGODB_PASSWORD=redhat
readonly MONGODB_DATABASE=redhatdb
readonly MONGODB_ADMIN_PASSWORD=redhat

function run_workload()
{
  local mongodb_ip
  mongodb_ip=$(oc get svc -n ${PROJECT_NAME} | grep -v glusterfs | grep mongodb | awk '{print $3}')
  local pod_name
  pod_name=$(oc get pods -n ${PROJECT_NAME} | grep mongodb | awk '{print $1}')
  oc -n ${PROJECT_NAME} exec $(oc get pod -n ${PROJECT_NAME} | grep ycsb | awk '{print $1}') -- \
  ./bin/ycsb run mongodb -s -threads ${YCSB_THREADS} \
  -P "workloads/${YCSB_WORKLOAD}" \
  -p mongodb.url=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${mongodb_ip}:27017/${MONGODB_DATABASE} 2>&1 \
  -p recordcount=${YCSB_RECORDCOUNT} \
  -p operationcount=${YCSB_OPERATIONCOUNT} \
  -p requestdistribution=${YCSB_DISTRIBUTION} \
  -p mongodb.writeConcern=acknowledged \
  -p wtimeout=10000 \
  -p writeallfields=true \
  -p maxexecutiontime=18000 | tee -a ${LOG_DIR}/mongodb_${pod_name}_run_${PROJECT_NAME}_${YCSB_WORKLOAD}_threads_${YCSB_THREADS}.log
}

run_workload
